### ISSUE TITLE
Nao consigo rodar

### ISSUE THREAD

**Issue by lucas231090** [jjesusfilho/stj#1]
Tento usar o exemplo e da 

 View(stj_baixar_cjsg)
> stj_baixar_cjsg(
+   dt_ini = "01/07/2019",
+   dt_fim = "30/07/2019"
+ )
Error in seq.default(1, pages, 10) : 'to' must be a finite number

**Comment by jjesusfilho** [comment]
Possivelmente, o pacote não está mais funcionando por conta do cloudflare.
